"""empty message

Revision ID: 37e65cbd546b
Revises: d81e78729682
Create Date: 2016-09-01 17:14:24.203451

"""

# revision identifiers, used by Alembic.
revision = '37e65cbd546b'
down_revision = 'd81e78729682'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    ### end Alembic commands ###
