"""empty message

Revision ID: d81e78729682
Revises: None
Create Date: 2016-07-05 18:51:24.825555

"""

# revision identifiers, used by Alembic.
revision = 'd81e78729682'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('botname', sa.String(length=20), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probot_botname'), 'probot', ['botname'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_probot_botname'), table_name='probot')
    op.drop_table('probot')
    ### end Alembic commands ###
